### ISSUE TITLE
Grammar and Tone Fix Needed: BuiltIn Functions

### ISSUE THREAD

**Issue by SujalChoudhari** [SujalChoudhari/CodaWiki#10]
The Wiki is not grammatically correct, neither is professional.
Need help in professionally writing the docs.

Extra: 
- Provide a cohesive experience for new learning developers
- The parameter types, return types (if any), should be explained.
- Use of tables to organize the name, parameters, description and return type

**Comment by th-shristi** [comment]
@SujalChoudhari Can i work on this? do assign me this!

**Comment by th-shristi** [comment]
@SujalChoudhari i have made a PR kindly review it
