### ISSUE TITLE
Grammar and Tone Fix Needed: Import Statements

### ISSUE THREAD

**Issue by SujalChoudhari** [SujalChoudhari/CodaWiki#15]
The Wiki is not grammatically correct, neither is professional.
Need help in professionally writing the docs.

Extra: Provide a cohesive experience for new learning developers

**Comment by th-shristi** [comment]
@SujalChoudhari Do assign me this! I want to contribute in this<

**Comment by th-shristi** [comment]
@SujalChoudhari made a PR do check it out.
