### ISSUE TITLE
Adding and Updating README.md file.

### ISSUE THREAD

**Issue by ira-mane** [SujalChoudhari/CodaWiki#23]
Hello @SujalChoudhari Can you assign me this ?
There is no readme file for the project .

**Comment by SujalChoudhari** [comment]
This is a wiki for a project,
[Coda](https://GitHub.com/SujalChoudhari/Coda)
You can view the Wiki in the Wiki section of that repo.

There is no readme required.
But the Home.md acts as a readme.

**Comment by ira-mane** [comment]
> This is a wiki for a project, [Coda](https://GitHub.com/SujalChoudhari/Coda) You can view the Wiki in the Wiki section of that repo.
> 
> There is no readme required. But the Home.md acts as a readme.

Ohh Thanks for the clarification 👍
