### ISSUE TITLE
Grammar and Tone Fix Needed: Operators

### ISSUE THREAD

**Issue by SujalChoudhari** [SujalChoudhari/CodaWiki#7]
The Wiki is not grammatically correct, neither is professional.
Need help in professionally writing the docs.

Extra: Provide a cohesive experience for new learning developers

**Comment by th-shristi** [comment]
I want to contribute in this. @SujalChoudhari can you assign this to me?

**Comment by SujalChoudhari** [comment]
Sure. 
There are a lot of operators to be taken care of. None should be missed and all of them should be easy to identify and placed in correct places.
I would suggest you to use tables, with columns; name,symbol,description,example.

**Comment by th-shristi** [comment]
Sure, I'll do it.

**Comment by SujalChoudhari** [comment]
@th-shristi There is a new addition of operator in v0.4.
The `in` operator. 
Added in [this commit](https://github.com/SujalChoudhari/Coda/commit/71ce048e1b4d08d86156b832103b083457cc7047)

**Comment by th-shristi** [comment]
@SujalChoudhari Updated the Operators.md kindly look into it and let me know if there are any further changes

**Comment by SujalChoudhari** [comment]
Checked the file, it will work.
Can you submit a pr for it?

**Comment by th-shristi** [comment]
@SujalChoudhari I've already submitted a pr for it! do merge it<

**Comment by SujalChoudhari** [comment]
Umm sorry @th-shristi,
The pull request is not submitted for the main branch of this repo.
You have submitted a PR for [your own repo](https://github.com/th-shristi/CodaWiki/pull/1).

**Comment by th-shristi** [comment]
@SujalChoudhari Is it done now?

**Comment by SujalChoudhari** [comment]
There is no pull request.
Once a pull request appears [here](https://github.com/SujalChoudhari/CodaWiki/pulls)
I will merge it.

**Comment by th-shristi** [comment]
@SujalChoudhari Made  a pr
